name: Generate pacman animation

on:
  schedule:
    - cron: "0 */6 * * *" 
  workflow_dispatch:
  
  push:
    branches:
    - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Generate pacman contribution graph
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: pulkitkash
          output_path: dist/pacman-contribution-graph.svg
          dark_output_path: dist/pacman-contribution-graph-dark.svg
          
      - name: Deploy to output branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
